Repository hmcts/sscs-ccd-definitions, pull requests merged in 2021-10, with the labels that each got.

#781 Sscs-9577: Bulk Scan: SSCS2 Form - Section 1: (YOUR DETAILS) - The Paying/Receiving/Other party fields
  benefit/VERSION.yaml
  benefit/data/sheets/CaseType/CaseType.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-781

#786 SSCS-9657 Supplementary response rip1 bugfix
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-z-audiovideo-nonprod.json
  benefit/data/sheets/CaseType/CaseType.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-786

#780 SSCS-9618 Child Support hide generate pdf event
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-780

#788 SSCS-9328 - Upload response fields shouldn't accept AV
  benefit/VERSION.yaml
  benefit/data/sheets/CaseType/CaseType.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-788

#789 SSCS-9675 Remove shouldBundleIncludeDocLink from av objects
  benefit/data/sheets/ComplexTypes/ComplexTypes-audiovideo-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-audiovideo-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-789
