Repository hmcts/sscs-ccd-definitions, pull requests merged in 2021-09, with the labels that each got.

#742 SSCS-9432 - Postponement request
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/FixedLists/FixedLists.json
  benefit/data/sheets/FixedLists/benefit/data/sheets/FixedLists/FixedLists-postponement-request-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-742

#754 Revert "Sscs 9433 postponement req"
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
  benefit/data/sheets/FixedLists/FixedLists-postponement-request-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-754

#756 SSCS-9495 Temp revert
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-756

#753 SSCS-9567: P1 – Flag to tell users that a case has been affected by t…
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/CaseType/CaseType.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-753

#760 Fixedlist fix
  benefit/data/sheets/FixedLists/FixedLists.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-760

#759 SSCS-9438-Merged master in
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/FixedLists/FixedLists.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-759

#751 Sscs 9442 unprocessed recording workbasket filter
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields-postponements-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-751

#731 SSCS-9519: Update List of Issue Codes
  benefit/VERSION.yaml
  benefit/data/sheets/CaseType/CaseType.json
  benefit/data/sheets/FixedLists/FixedLists.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-731

#765 Sscs 9439 action postponement request event grant postponement
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/FixedLists/FixedLists.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-765

#764 SSCS-9436 Offline postponement request send to interloc
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/FixedLists/FixedLists-postponement-request-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-764

#770 SSCS-9601 Child maintenance number
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseField/CaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-770

#771 Sscs 9433 postponement req
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
  benefit/data/sheets/FixedLists/FixedLists-postponement-request-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields-postponements-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-771

#774 SSCS-9433- tag version set
  benefit/VERSION.yaml
  benefit/data/sheets/CaseType/CaseType.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-774

#728 SSCS-9374: Upload Hearing Recording Event - Overwrite Existing Recordings
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-728

#775 Bump up the version number
  benefit/VERSION.yaml
  benefit/data/sheets/CaseType/CaseType.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-775

#768 SSCS - 9581 - retain hidden value for interlocReferralReason and dwpEd…
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseType/CaseType.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-768

#758 Revert "SSCS-9495 Temp revert"
  benefit/VERSION.yaml
  benefit/data/sheets/CaseType/CaseType.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-758

#778 SSCS-9561- change event name
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseType/CaseType.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-778

#767 SSCS-9133 - Add admin events to 'Not listable' state
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseType/CaseType.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-767

#766 SSCS-9134 - Update permissions for 'Not listable' and 'Update not listable'
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-766

#750 SSCS-9552: Modify MYA links for demo environment
  benefit/VERSION.yaml
  benefit/data/sheets/CaseType/CaseType.json
  bin/create-xlsx.sh
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-750
