Repository hmcts/sscs-ccd-definitions, pull requests merged in 2021-11, with the labels that each got.

#802 SSCS-9642 Notifications – Abate letter
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseType/CaseType.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-802

#811 sscs 9627 added a preview tag
  Jenkinsfile_CNP
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-811

#812 SSCS-9740: ExUI – Allow superusers to manage audio visual evidence
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseType/CaseType.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-812

#805 Sscs 9677 add original sender
  benefit/VERSION.yaml
  benefit/data/sheets/CaseType/CaseType.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-805

#810 SSCS-9732: Case loader – Add venue ID when saving hearing data
  benefit/VERSION.yaml
  benefit/data/sheets/CaseType/CaseType.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-810

#806 SSCS-9668 Added child support confidentiality to edited response reason
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-dwpUploadResponse.json
  benefit/data/sheets/CaseType/CaseType.json
  benefit/data/sheets/FixedLists/FixedLists-child-support-upload-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-806
