Repository hmcts/sscs-ccd-definitions, pull requests merged in 2022-12, with the labels that each got.

#1109 SSCS-10937-2 - Remove Bundles Tab for FTA
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1109

#1033 SSCS-10562 update Child Support to Child Support Agency
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/FixedLists/FixedLists.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1033

#1111 Fix Vulnerabilities
  package.json
  yarn-audit-issues-result
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1111

#1104 SSCS-11092 adds adjournmentInProgress to definitions
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-sandl-nonprod.json
  benefit/data/sheets/CaseField/CaseField-sandl-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1104

#1116 Sscs 10866 revert
  benefit/VERSION.yaml
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1116
