Repository hmcts/sscs-ccd-definitions, pull requests merged in 2022-11, with the labels that each got.

#1084 SSCS-11086 Fix CCD pipeline to fail on incorrect upload
  build.gradle
  src/test/java/benefit/HighLevelDataSetupApp.java
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1084

#1047 SSCS-10542 Set Aside
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-sandl-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-sandl-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-sandl-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-sandl-nonprod.json
  benefit/data/sheets/CaseField/CaseField-sandl-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-sandl-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-sandl-nonprod.json
  benefit/data/sheets/FixedLists/FixedList-sandl-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-sandl-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists.json
  benefit/data/sheets/State/State-sandl-nonprod.json
  benefit/data/sheets/State/State.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1047

#1074 SSCS-10937 - Remove Bundles Tab for FTA
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1074

#1090 Revert "SSCS-10937 - Remove Bundles Tab for FTA"
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1090

#1087 Uploaded image for project: 'Reform-SSCS'
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1087

#1043 SSCS-10853 Hearing Postponed Event Change
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1043
