Repository hmcts/sscs-ccd-definitions, pull requests merged in 2023-10, with the labels that each got.

#1466 SSCSCI-99
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1466

#1453 SSCS-11996 - Release PR for ccd-defs.
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField-nonprod.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab-nonprod.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1453

#1479 CCD: fix
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseField/CaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1479

#1481 add changes
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-dwpUploadResponse.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-posthearing-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-posthearing-nonprod.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields.json
  charts/sscs-ccd-definitions/Chart.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1481
