Repository hmcts/sscs-ccd-definitions, pull requests merged in 2023-09, with the labels that each got.

#1331 Sscs 11683 update send to judge
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-WA-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseField/CaseField-WA-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-WA-nonprod.json
Labels: ns:sscs, prd:sscs

#1425 SSCS-11697 - Do not update the 'FTA Further Evidence State' or the FTA state if original sender is FTA
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1425

#1443 SSCSCI-175: upgrade node to v18
  .nvmrc
  Jenkinsfile_CNP
  e2e-tests/Jenkinsfile_CNP
  e2e-tests/Jenkinsfile_nightly
  e2e-tests/package.json
  e2e-tests/tsconfig-base.json
  e2e-tests/yarn.lock
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1443

#1248 make generate upload radio buttons
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-posthearingb-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearing-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-writeFinalDecisionNotice.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearing-nonprod.json
  benefit/data/sheets/State/State-posthearing-nonprod.json
  benefit/data/sheets/State/State-posthearingb-nonprod.json
  benefit/data/sheets/State/State.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1248

#1394 CCD: add prepost hearing
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1394

#1195 SSCS-10865: Added arepanelmembersexcluded
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
  benefit/data/sheets/CaseField/CaseField-nonprod.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab-nonprod.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1195

#1449 Sscs 10593 grant refuse pta remake
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearing-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearingb-nonprod.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearingb-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1449

#1423 Sscs 11377 signed fields for pta
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearingb-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearingb-nonprod.json
  benefit/data/sheets/CaseField/CaseField-posthearingb-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearingb-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1423

#1452 Revert "SSCS-11585 - Dropdown List for Language selection values in update to case data"
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1452

#1454 revert change
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1454

#1455 complete revert
  benefit/VERSION.yaml
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles.json
  bin/upload-ccd-definition-to-env.sh
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1455

#1435 SSCSCI 93
  benefit/VERSION.yaml
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1435

#1387 SSCS-11855 - Manually created cases should have the correct hearing route
  benefit/VERSION.yaml
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1387

#1446 CCD: fix up ccd defs
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearing-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/FixedLists/FixedLists-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearingb-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1446

#1462 SSCSCI-93
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1462

#1463 version bump
  benefit/VERSION.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1463

#1260 Sscs 10581 admin can process correction or send a correction request to judge for review
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearing-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1260

#1447 CCD: add remit from ut
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEvent/CaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-posthearing-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-posthearingb-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
  benefit/data/sheets/FixedLists/FixedLists-posthearingb-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1447

#1470 renovate fix
  .github/renovate.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1470

#1457 SSCS-11999 Set CRUD for amendReasons for clerk
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1457

#1475 Cve suppress
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1475

#1459 CCD: readd changes
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles.json
  bin/upload-ccd-definition-to-env.sh
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1459
