Repository hmcts/sscs-ccd-definitions, pull requests merged in 2023-06, with the labels that each got.

#1355 SSCS-11747 - Add ShowEventNotes to all the events
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEvent/CaseEvent.json
  e2e-tests/package.json
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1355

#1337 Sscs 10603 admin can upload lta
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearingb-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearing-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearingb-nonprod.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseField/CaseField-posthearingb-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-posthearing-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-posthearingb-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-posthearing-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-posthearingb-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearingb-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1337

#1360 SSCS-11756 - Re enable functional tests
  e2e-tests/e2e/features.crossbrowser.conf.ts
  e2e-tests/e2e/features/lapse-case.feature
  e2e-tests/e2e/features/step_definitions/case-access-management.steps.ts
  e2e-tests/e2e/features/step_definitions/issue-decision.steps.ts
  e2e-tests/e2e/features/step_definitions/issue-directions-notice.steps.ts
  e2e-tests/e2e/features/step_definitions/response-reviewed.steps.ts
  e2e-tests/e2e/features/step_definitions/ucb-and-subscription.steps.ts
  e2e-tests/e2e/features/step_definitions/update-case-data.steps.ts
  e2e-tests/e2e/features/update-other-party-reasonable-adjustments.feature
  e2e-tests/e2e/features/update-subscriptions.feature
  e2e-tests/e2e/features/upload-document-evidence.feature
  e2e-tests/e2e/features/upload-response-with-further-info.feature
  e2e-tests/e2e/features/upload-response-without-further-info.feature
  e2e-tests/e2e/flows/authentication.flow.ts
  e2e-tests/e2e/pages/adjournment.page.ts
  e2e-tests/e2e/reporter/Report.html
  e2e-tests/e2e/support/hooks.ts
  e2e-tests/package.json
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1360

#1370 SSCS-11766 - Add ShowEventNotes to all the events
  benefit/VERSION.yaml
  bulkscan/data/sheets/CaseEvent.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1370

#1271 SSCS-10973 - rename requestInfoIncompleteApplication to Requestforinformation
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1271

#1309 Sscs 11431 post hearings gaps
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEvent/CaseEvent-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearingb-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1309

#1376 SSCS-11784-Update-issue-directions-labels
  benefit/VERSION.yaml
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/FixedLists/FixedLists.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1376

#1250 SSCS-11101 Create Task "Review Incomplete Appeal"
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1250

#1259 SSCS-1104-review-information-reqeusted
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1259

#1278 SSCS-11107 Review FTA Response
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-dwpUploadResponse.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1278

#1310 SSCS-11110-1-1125-action-unprocessed-correspondence
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1310

#1291 SSCS-11112 Review Bi-Lingual Document
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-WA-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1291

#1297 SSCS-11115 Create Task "Issue Outstanding Translation"
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1297

#1295 SSCS-11118 Create Task "Review Admin Action" for CTSC Administrator
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1295

#1318 SSCS-11129 Publish events
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1318

#1302 SSCS-11123 Create Task "Review FTA Due Date"
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-WA-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1302

#1325 SSCS-11132-review-robotic-fail
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1325

#1329 SSCS 11120 review bf date
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-WA-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-WA-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1329

#1377 SSCS-11663 Nightly task to trigger CCD events
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-WA-noprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-WA-noprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-WA-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1377

#1336 SSCS 11135 create bundle and allocate case roles
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-WA-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-WA-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1336
