Repository hmcts/sscs-ccd-definitions, pull requests merged in 2023-02, with the labels that each got.

#1142 SSCS-10539 - Add setAsideApplication to fixed lists for Action Further Evidence
  benefit/data/sheets/FixedLists/FixedLists-setaside-application-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1142

#1106 SSCS-10295 change adjournCaseInterpreterLanguage type to DynamicList
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1106

#1146 Sscs 10893 reserve to judge field
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-sandl-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-sandl-nonprod.json
  benefit/data/sheets/CaseField/CaseField-sandl-nonprod.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab-sandl-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-sandl-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-sandl-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1146

#1186 SSCS-11393 - Refactor post hearings into their own nonprod files instead of sandl release.
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-sandl-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-sandl-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-sandl-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearing-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-sandl-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-sandl-nonprod.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseField/CaseField-sandl-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-posthearing-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-sandl-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-posthearing-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-sandl-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-sandl-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-setaside-application-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1186

#1189 S&L Definitions Release
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-sandl-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-sandl-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-sandl-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState.json
  benefit/data/sheets/CaseEvent/CaseEvent-sandl-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-dwpUploadResponse-sandl-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-dwpUploadResponse.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-sandl-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField-sandl-nonprod.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab-sandl-nonprod.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-sandl-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-sandl-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
  benefit/data/sheets/FixedLists/FixedLists-postponement-request-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-sandl-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists.json
  benefit/data/sheets/SearchResultFields/SearchResultFields-sandl-nonprod.json
  benefit/data/sheets/SearchResultFields/SearchResultFields.json
  benefit/data/sheets/State/State-posthearing-nonprod.json
  benefit/data/sheets/State/State.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields-postponements-nonprod.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields-sandl-nonprod.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields.json
  benefit/data/sheets/WorkBasketResultFields/WorkBasketResultFields-sandl-nonprod.json
  benefit/data/sheets/WorkBasketResultFields/WorkBasketResultFields.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1189

#1134 SSCS-11276 - Update bexleyheaths venue entry EPIMS ID
  benefit/data/sheets/FixedLists/FixedLists.json
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1134

#1197 SSCS-11393 : Added add a hearing event to prod files
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1197

#1132 SSCS-10653 - FTA - Upload response doesn't change state
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1132

#1205 SSCS-11480 : Swapped to new bundling service demo url
  bin/before-data-setup-step.sh
  bin/create-xlsx.sh
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1205
