Repository hmcts/sscs-ccd-definitions, pull requests merged in 2023-11, with the labels that each got.

#1483 put in correct sheet
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1483

#1487 fixed postopementDetails being null in about to submit
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1487

#1458 SSCS-11728 / SSCS-11966 Benefit type changes
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1458

#1490 added benefitSelection for incompleteApplicationReceived event
  benefit/VERSION.yaml
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1490

#1486 SSCS-12022 - Post Hearings Release Merge Prep
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearingb-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearing-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearingb-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseField/CaseField-posthearingb-nonprod.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-posthearing-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-posthearingb-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-posthearing-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-posthearingb-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
  benefit/data/sheets/FixedLists/FixedLists-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearingb-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1486

#1493 CCD: remake branch
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1493

#1477 CCD: rename add a hearing to listing request sent
  benefit/VERSION.yaml
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1477

#1499 Revert "CCD: rename add a hearing to listing request sent"
  benefit/VERSION.yaml
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1499
