Repository hmcts/sscs-ccd-definitions, pull requests merged in 2023-04, with the labels that each got.

#1256 SSCS-11577 - Update authorisations for post hearing case fields in nonProd files
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1256

#1258 SSCS-11592 - Fix for bulkscan Case Types Not Having AccessProfile Roles
  bulkscan/VERSION.yaml
  bulkscan/data/ccd-template.xlsx
  bulkscan/data/sheets/AuthorisationCaseType.json
  bulkscan/data/sheets/RoleToAccessProfiles.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1258

#1193 SSCS-10544: Added new config of set aside grant
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1193

#1204 SSCS-11384 - Add Confirm panel composition to interlocReferralReason …
  benefit/VERSION.yaml
  benefit/data/sheets/FixedLists/FixedLists.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1204

#1261 Fix pipeline
  build.gradle
  src/test/java/benefit/ProdTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1261

#1262 Pipeline fixture
  bin/before-data-setup-step.sh
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1262

#1265 Pipeline fixture
  build.gradle
  src/test/java/benefit/ProdTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1265

#1266 Increase API callout time
  e2e-tests/config/default.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1266

#1218 Sscs 10984 creating new body content for correction
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-posthearing-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1218

#1281 Point back at old ccd-definition-processor
  Dockerfile
  benefit/VERSION.yaml
  docker/importer.Dockerfile
  docker/xlsx2json.Dockerfile
  e2e-tests/.nsprc
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1281

#1268 SSCS-11592 - Updates to fix bulkscan related issues
  bin/before-data-setup-step.sh
  bin/create-xlsx.sh
  bin/upload-ccd-definition-to-env.sh
  bulkscan/VERSION.yaml
  bulkscan/data/ccd-template.xlsx
  bulkscan/data/sheets/AuthorisationCaseField.json
  bulkscan/data/sheets/AuthorisationCaseType.json
  bulkscan/data/sheets/CaseEvent.json
  bulkscan/data/sheets/CaseEventToComplexTypes.json
  bulkscan/data/sheets/CaseEventToFields.json
  bulkscan/data/sheets/CaseField.json
  bulkscan/data/sheets/CaseType.json
  bulkscan/data/sheets/CaseTypeTab.json
  bulkscan/data/sheets/FixedLists.json
  bulkscan/data/sheets/Jurisdiction.json
  bulkscan/data/sheets/RoleToAccessProfiles.json
  bulkscan/data/sheets/SearchInputFields.json
  bulkscan/data/sheets/SearchResultFields.json
  bulkscan/data/sheets/WorkBasketInputFields.json
  bulkscan/data/sheets/WorkBasketResultFields.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1268

#1293 Update HighLevelDataSetupApp.java
  src/test/java/benefit/HighLevelDataSetupApp.java
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1293

#1294 Fix ccd-definition-processor and yarn upgrade :)
  .gitignore
  .yarn/releases/yarn-3.5.0.cjs
  .yarnrc.yml
  Dockerfile
  benefit/data/~$ccd-template.xlsx
  bin/before-data-setup-step.sh
  charts/sscs-ccd-definitions/Chart.yaml
  docker/importer.Dockerfile
  docker/xlsx2json.Dockerfile
  e2e-tests/package.json
  e2e-tests/yarn.lock
  package.json
  sonar-project.properties
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1294

#1138 SSCS-10007: non prod version of ccd changes for Issue Generic Letter
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEvent/CaseEvent-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1138

#1299 Update HighLevelDataSetupApp.java
  src/test/java/benefit/HighLevelDataSetupApp.java
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1299

#1300 removed empty line, version bump
  benefit/VERSION.yaml
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
  bin/before-data-setup-step.sh
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1300
