Repository hmcts/sscs-ccd-definitions, pull requests merged in 2023-05, with the labels that each got.

#1301 E2e fix
  e2e-tests/.eslintignore
  e2e-tests/.gitignore
  e2e-tests/.prettierignore
  e2e-tests/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  e2e-tests/.yarn/releases/yarn-3.5.0.cjs
  e2e-tests/.yarnrc.yml
  e2e-tests/e2e/support/hooks.ts
  e2e-tests/e2e/tsconfig.json
  e2e-tests/package.json
  e2e-tests/tsconfig.json
  e2e-tests/yarn.lock
  package.json
  src/test/java/benefit/HighLevelDataSetupApp.java
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1301

#1304 definition processort updated to latest
  docker/importer.Dockerfile
  docker/xlsx2json.Dockerfile
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1304

#1272 add post hearing journeys into prod
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseField/CaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1272

#1306 adding missing commas, version bump
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseField/CaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1306

#1307 Sscs 10523 sor request
  benefit/VERSION.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1307

#1312 Sscs5 release hotfix
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseField/CaseField.json
  src/test/java/benefit/HighLevelDataSetupApp.java
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1312

#1290 SSCS-11601 - trigger ccdMidEvent for upload response for other parties
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-dwpUploadResponse.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1290

#1296 SSCS-11603 - Allow user to set interlocReferralReason during send to interloc event
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1296

#1314 Increment version
  benefit/VERSION.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1314

#1315 importer Dockerfile fix
  docker/importer.Dockerfile
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1315

#1321 Version bump
  benefit/VERSION.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1321

#1316 SSCS-11611 - Make Hearing Type filter on case list page available for FTA
  benefit/VERSION.yaml
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1316

#1139 SSCS-10792 - Improve the way confidentiality marker/flags are displayed to the user
  benefit/VERSION.yaml
  benefit/data/sheets/CaseField/CaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1139
