Repository hmcts/sscs-ccd-definitions, pull requests merged in 2023-01, with the labels that each got.

#1101 SSCS-10989 - New Filter for cases - list assist case or gaps case
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseField/CaseField-nonprod.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields-sandl-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1101

#1121 SSCS-11090 listing error
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-sandl-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-sandl-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-sandl-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/State/State-sandl-nonprod.json
  benefit/data/sheets/State/State.json
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1121

#1130 Sscs 10989 - New Filter for cases - list assist case or gaps case (Moving to prod files)
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseField/CaseField-nonprod.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields-sandl-nonprod.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1130

#1136 Listing error Event type in the correct position SSCS-11325
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEvent/CaseEvent-sandl-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1136

#1125 Sscs 11257 update venues to align with spreadsheet
  benefit/data/sheets/FixedLists/FixedLists.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1125
