Repository hmcts/sscs-ccd-definitions, pull requests merged in 2023-03, with the labels that each got.

#1212 SSCS-11493 : Updated nodejs helm version from 2.4.11 to 2.4.14
  charts/sscs-ccd-definitions/Chart.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1212

#1211 SSCS-11393 : Temporarily turn off DWP access to upload response event…
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1211

#1214 SSCS-11393 - Turn On DWP Access
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1214

#1135 SSCS-9939 - Access Profiles & HMRC Response Writer Integration
  benefit/VERSION.yaml
  benefit/data/ccd-template.xlsx
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-hmrc-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-hmrc-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-hmrc-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState.json
  benefit/data/sheets/AuthorisationCaseType/AuthorisationCaseType-nonshuttered.json
  benefit/data/sheets/AuthorisationCaseType/AuthorisationCaseType-shuttered.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearing-nonprod.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles-hmrc-nonprod.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles.json
  benefit/data/sheets/SearchInputFields/SearchInputFields-hmrc-nonprod.json
  benefit/data/sheets/SearchInputFields/SearchInputFields.json
  benefit/data/sheets/SearchResultFields/SearchResultFields-hmrc-nonprod.json
  benefit/data/sheets/SearchResultFields/SearchResultFields.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields-hmrc-nonprod.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields.json
  benefit/data/sheets/WorkBasketResultFields/WorkBasketResultFields-hmrc-nonprod.json
  benefit/data/sheets/WorkBasketResultFields/WorkBasketResultFields.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1135

#1217 Fix name for auth case field file
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1217

#1221 Revert 9939 Changes
  benefit/VERSION.yaml
  benefit/data/ccd-template.xlsx
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-hmrc-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-hmrc-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-hmrc-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState.json
  benefit/data/sheets/AuthorisationCaseType/AuthorisationCaseType-nonshuttered.json
  benefit/data/sheets/AuthorisationCaseType/AuthorisationCaseType-shuttered.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearing-nonprod.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles-hmrc-nonprod.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles.json
  benefit/data/sheets/SearchInputFields/SearchInputFields-hmrc-nonprod.json
  benefit/data/sheets/SearchInputFields/SearchInputFields.json
  benefit/data/sheets/SearchResultFields/SearchResultFields-hmrc-nonprod.json
  benefit/data/sheets/SearchResultFields/SearchResultFields.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields-hmrc-nonprod.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields.json
  benefit/data/sheets/WorkBasketResultFields/WorkBasketResultFields-hmrc-nonprod.json
  benefit/data/sheets/WorkBasketResultFields/WorkBasketResultFields.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1221

#1200 SSCS-10822 implements reservedDistrictTribunalJudge
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1200

#1150 change adjourn panel member fields to judicial users
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1150

#1147 Sscs 10983 set aside document generated
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1147

#1226 SSCS-11542 : Give everyone access to handling error case states
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1226

#1199 update heading SSCS-10543
  benefit/data/sheets/ComplexTypes/ComplexTypes-posthearing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1199

#1227 add back text fields and put judicial users in nonprod SSCS-11543
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-adjournment-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField-adjournment-nonprod.json
  benefit/data/sheets/CaseField/CaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1227

#1228 SSCS-11531 - AccessProfiles Updates for Citizen Failing Functional Tests
  README.md
  benefit/VERSION.yaml
  benefit/data/ccd-template.xlsx
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-hmrc-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-adjournment-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-hmrc-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-hmrc-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState.json
  benefit/data/sheets/AuthorisationCaseType/AuthorisationCaseType-nonshuttered.json
  benefit/data/sheets/AuthorisationCaseType/AuthorisationCaseType-shuttered.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearing-nonprod.json
  benefit/data/sheets/CaseRoles/CaseRoles-nonprod.json
  benefit/data/sheets/CaseRoles/CaseRoles.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles-hmrc-nonprod.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles.json
  benefit/data/sheets/SearchInputFields/SearchInputFields-hmrc-nonprod.json
  benefit/data/sheets/SearchInputFields/SearchInputFields.json
  benefit/data/sheets/SearchResultFields/SearchResultFields-hmrc-nonprod.json
  benefit/data/sheets/SearchResultFields/SearchResultFields.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields-hmrc-nonprod.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields.json
  benefit/data/sheets/WorkBasketResultFields/WorkBasketResultFields-hmrc-nonprod.json
  benefit/data/sheets/WorkBasketResultFields/WorkBasketResultFields.json
  bulkscan/data/sheets/AuthorisationCaseEvent.json
  bulkscan/data/sheets/AuthorisationCaseField.json
  bulkscan/data/sheets/AuthorisationCaseState.json
  bulkscan/data/sheets/AuthorisationCaseType.json
  bulkscan/data/sheets/AuthorisationComplexType.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1228

#1242 add to prod and bump
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-adjournment-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseField/CaseField-adjournment-nonprod.json
  benefit/data/sheets/CaseField/CaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1242

#1243 npm request bump down
  benefit/VERSION.yaml
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1243

#1251 SSCS-11566 : Changed admin send to hearing event to be accessible by …
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1251
