Repository hmcts/sscs-ccd-definitions, pull requests merged in 2023-08, with the labels that each got.

#1428 Added field and published events for SSCS-11873
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-WA-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-WA-nonprod.json
  benefit/data/sheets/CaseField/CaseField-WA-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1428

#1431 fix e2e tests for sent to interloc ccd submit
  e2e-tests/e2e/features/step_definitions/issue-directions-notice.steps.ts
  e2e-tests/e2e/features/step_definitions/send-to-interloc.steps.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1431

#1357 SSCS-11721 - Java 17
  .github/workflows/gradle.yml
  benefit/VERSION.yaml
  build.gradle
  jitpack.yml
  src/test/java/benefit/ProdTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1357

#1352 SSCS-10526 write statement of reasons
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearing-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1352

#1427 Sscs 11348 ut decision refused
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearingb-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-posthearing-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearingb-nonprod.json
  benefit/data/sheets/CaseField/CaseField-posthearingb-nonprod.json
  benefit/data/sheets/ComplexTypes/ComplexTypes-posthearingb-nonprod.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-posthearingb-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearingb-nonprod.json
  benefit/data/sheets/State/State-posthearing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1427

#1373 SSCS-11336 Get first tier documents for UT
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-posthearingb-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent-posthearingb-nonprod.json
  benefit/data/sheets/State/State-posthearingb-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1373

#1392 SSCS-11366 Add signedBy and signedRole fields
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearing-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-posthearingb-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearingb-nonprod.json
  benefit/data/sheets/CaseField/CaseField-posthearing-nonprod.json
  benefit/data/sheets/CaseField/CaseField-posthearingb-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1392

#1422 Sscs 11376 write sor signed fields
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1422

#1247 SSCS-10766 - Create Set Aside Granted Document - CALL
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-posthearing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1247

#1395 Sscs 11486 add ph review types
  benefit/VERSION.yaml
  benefit/data/sheets/FixedLists/FixedLists-posthearing-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists-posthearingb-nonprod.json
  benefit/data/sheets/FixedLists/FixedLists.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1395

#1319 SSCS-10027 Create task "Review Confidentiality Request"
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-WA-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-WA-nonprod.json
  benefit/data/sheets/CaseField/CaseField-WA-nonprod.json
Labels: ns:sscs, prd:sscs

#1326 SSCS-10048 Create "Review PHE Request" Task for Judge
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-dwpUploadResponse.json
Labels: ns:sscs, prd:sscs
