Repository hmcts/sscs-ccd-definitions, pull requests merged in 2024-04, with the labels that each got.

#1533 'Void case' end state should be dormant
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1533

#1547 Fix yarn deps
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1547

#1542 CVE dependency patches and minors
  Jenkinsfile_CNP
  e2e-tests/package.json
  e2e-tests/yarn-audit-known-issues
  e2e-tests/yarn.lock
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1542

#1548 SSCSSI-156 Remove references to unused sscs orchestrator
  bin/before-data-setup-step.sh
  bin/create-xlsx.sh
  bin/template-urls.sh
  bin/upload-ccd-definition-to-env.sh
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1548

#1554 Hot fix to not run tests in preview env
  Jenkinsfile_CNP
  bin/run-functional-tests.sh
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1554

#1476 Sscs 12006 work allocation ph tasks
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-WA.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-testing-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-GS-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-WA.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-GS.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-WA.json
  benefit/data/sheets/AuthorisationCaseType/AuthorisationCaseType-nonshuttered.json
  benefit/data/sheets/CaseEvent/CaseEvent-WA.json
  benefit/data/sheets/CaseEvent/CaseEvent-testing-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-WA.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-dwpUploadResponse.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-testing-noprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField-WA.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-WA.json
  benefit/data/sheets/FixedLists/FixedLists-WA.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles-GS.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles-WA-fee-paid.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles-WA.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields-WA.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1476

#1562 Implement logging to the framework
  .gitignore
  functional-test/api/client/appealTypeFactory.ts
  functional-test/common/webActions.ts
  functional-test/config/playwright.config.ts
  functional-test/pages/common/homePage.ts
  functional-test/utils/loggerUtil.ts
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1562
