Repository hmcts/sscs-ccd-definitions, pull requests merged in 2024-09, with the labels that each got.

#1727 Sscssi 375
  functional-test/api/client/sscs/factory/appeal.type.factory.ts
  functional-test/api/data/payload/create-appeal/pip_sya_welsh.json
  functional-test/e2e/api-test-client.spec.ts
  functional-test/e2e/urgent-hearing.spec.ts
  functional-test/fixtures/steps/urgent.hearing.ts
  functional-test/pages/tabs/appealDetails.ts
  functional-test/pages/tabs/documents.ts
  functional-test/pages/tabs/history.ts
  functional-test/pages/tabs/summary.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1727

#1731 fix docker curl issue by reinstalling curl to base image
  benefit/VERSION.yaml
  docker/importer.Dockerfile
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1731

#1733 Update express to 4.20.0
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1733

#1767 Disable HLD on master
  Jenkinsfile_CNP
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1767
