Repository hmcts/sscs-ccd-definitions, pull requests merged in 2024-06, with the labels that each got.

#1595 SSCSSI-310 - implement new jenkins step
  Jenkinsfile_CNP
  functional-test/api/client/sscs/factory/appeal.type.factory.ts
  functional-test/common/web.action.ts
  functional-test/e2e/upload-response.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/confirm.case.lapsed.ts
  functional-test/fixtures/steps/evidence.reminder.ts
  functional-test/fixtures/steps/listing.error.ts
  functional-test/fixtures/steps/note.ts
  functional-test/fixtures/steps/send.to.admin.ts
  functional-test/fixtures/steps/upload.response.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/common/loginPage.ts
  functional-test/pages/tabs/history.ts
  functional-test/pages/tabs/summary.ts
  functional-test/pages/upload.response.page.ts
  functional-test/playwright.config.ts
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1595

#1597 refactor: adding the hook methods to the tests.
  Jenkinsfile_CNP
  functional-test/api/client/sscs/appeal.event.ts
  functional-test/api/client/sscs/factory/appeal.update.factory.ts
  functional-test/common/web.action.ts
  functional-test/config/config.ts
  functional-test/e2e/add-note.spec.ts
  functional-test/e2e/case-dormant.spec.ts
  functional-test/e2e/confirm-case-lapsed.spec.ts
  functional-test/e2e/evidence-reminder.spec.ts
  functional-test/e2e/listing-error.spec.ts
  functional-test/e2e/send-to-admin.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/confirm.case.lapsed.ts
  functional-test/fixtures/steps/evidence.reminder.ts
  functional-test/fixtures/steps/listing.error.ts
  functional-test/fixtures/steps/note.ts
  functional-test/fixtures/steps/send.to.admin.ts
  functional-test/fixtures/steps/upload.response.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/common/loginPage.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1597

#1604 Fix upload response test
  functional-test/config/config.ts
  functional-test/e2e/upload-response.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/upload.response.ts
  functional-test/pages/common/loginPage.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1604

#1605 Refactor login cookies
  functional-test/common/web.action.ts
  functional-test/e2e/add-note.spec.ts
  functional-test/e2e/send-to-judge.spec.ts
  functional-test/fixtures/steps/associate-case.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/confirm.case.lapsed.ts
  functional-test/fixtures/steps/evidence.reminder.ts
  functional-test/fixtures/steps/listing.error.ts
  functional-test/fixtures/steps/note.ts
  functional-test/fixtures/steps/send.to.admin.ts
  functional-test/fixtures/steps/send.to.judge.ts
  functional-test/fixtures/steps/upload.response.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/common/loginPage.ts
  functional-test/pages/tabs/appealDetails.ts
  functional-test/pages/upload.response.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1605

#1600 SSCSSI-327: Add Test Case Dormant Event
  functional-test/e2e/send-to-dormant.spec.ts
  functional-test/e2e/upload-response.spec.ts
  functional-test/fixtures/steps/send.to.dormant.ts
  functional-test/lib/steps.factory.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1600

#1549 SSCSCI-499: upgrade chart version
  charts/sscs-ccd-definitions/Chart.yaml
  charts/sscs-ccd-definitions/values.yaml
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1549

#1608 SSCSSI-189: Add test for "Send to With FTA" event
  functional-test/e2e/send-to-fta.spec.ts
  functional-test/fixtures/steps/send.to.fta.ts
  functional-test/lib/steps.factory.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1608

#1603 SSCSSI 329: Test Strike Out Case Event
  functional-test/e2e/listing-error.spec.ts
  functional-test/e2e/strike.out.case.spec.ts
  functional-test/fixtures/steps/strike.out.case.ts
  functional-test/lib/steps.factory.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1603

#1550 SSCSCI-768: Hearing date/time for GAPS cases
  benefit/VERSION.yaml
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1550

#1611 add helper method of upload response step to be re-used for other tests
  functional-test/fixtures/steps/upload.response.ts
  functional-test/helpers/stepsHelper.ts
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1611

#1592 [SSCSSI-265]: Review admin action work allocation task tests
  .gitignore
  Jenkinsfile_CNP
  functional-test/config/config.ts
  functional-test/e2e/associate-case.spec.ts
  functional-test/e2e/work-allocation/wa.review.admin.action.task.spec.ts
  functional-test/fixtures/steps/associate-case.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/information.received.ts
  functional-test/fixtures/steps/note.ts
  functional-test/fixtures/steps/send.to.admin.ts
  functional-test/fixtures/steps/work-allocation/review.admin.action.task.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/allocate.ctsc.role.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/allocate.ctsc.role_en.json
  functional-test/pages/content/assign.task_en.json
  functional-test/pages/content/information.received_en.json
  functional-test/pages/content/review.admin.task_en.json
  functional-test/pages/information.received.page.ts
  functional-test/pages/tabs/history.ts
  functional-test/pages/tabs/tasks.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1592

#1617 add request time extension tests
  functional-test/e2e/request-time-extension.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/request.time.extension.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/request.time.extension_en.json
  functional-test/pages/request.time.extension.page.ts
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1617

#1614 Add Caching
  functional-test/api/client/idam/idam.service.ts
  functional-test/api/client/sscs/appeal.event.ts
  functional-test/api/client/sscs/factory/appeal.update.factory.ts
  functional-test/e2e/case-dormant.spec.ts
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1614

#1610 SSCSSI 217: Appeal Withdrawn Event
  functional-test/e2e/appeal-withdrawn.spec.ts
  functional-test/fixtures/steps/appeal.withdrawn.ts
  functional-test/lib/steps.factory.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1610

#1621 feat: add all the api driven payload to upload a response.
  functional-test/api/client/idam/idam.service.ts
  functional-test/api/client/sscs/factory/appeal.update.factory.ts
  functional-test/api/data/payload/upload-response/upload-response.json
  functional-test/e2e/api-test-client.spec.ts
  functional-test/e2e/associate-case.spec.ts
  functional-test/e2e/case-dormant.spec.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1621

#1622 [SI-272]: add listing error work allocation task e2e tests
  functional-test/e2e/work-allocation/wa.review.listing.error.task.spec.ts
  functional-test/fixtures/steps/listing.error.ts
  functional-test/fixtures/steps/ready.to.list.ts
  functional-test/fixtures/steps/void.case.ts
  functional-test/fixtures/steps/work-allocation/review.listing.error.task.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/review.listing.error.task_en.json
  functional-test/pages/tabs/history.ts
  functional-test/pages/tabs/tasks.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1622

#1625 fix flaky listing error task tests
  functional-test/e2e/work-allocation/wa.review.listing.error.task.spec.ts
  functional-test/fixtures/steps/listing.error.ts
  functional-test/fixtures/steps/ready.to.list.ts
  functional-test/fixtures/steps/void.case.ts
  functional-test/fixtures/steps/work-allocation/review.listing.error.task.ts
  functional-test/pages/tabs/tasks.ts
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1625

#1616 Minor and patch upgrades to fix CVEs
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1616

#1624 Extend Fixed list to include new epim ids for Edinburgh and Romford
  benefit/VERSION.yaml
  benefit/data/sheets/FixedLists/FixedLists.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1624

#1630 [SI-262]: add review FTA response task work allocation tests
  functional-test/common/web.action.ts
  functional-test/e2e/upload-response.spec.ts
  functional-test/e2e/work-allocation/wa.review.admin.action.task.spec.ts
  functional-test/e2e/work-allocation/wa.review.listing.error.task.spec.ts
  functional-test/fixtures/steps/upload.response.ts
  functional-test/helpers/stepsHelper.ts
  functional-test/pages/common/check.your.answers.page.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/common/loginPage.ts
  functional-test/pages/content/review.fta.response.task_en.json
  functional-test/pages/tabs/history.ts
  functional-test/pages/tabs/tasks.ts
  functional-test/pages/upload.response.page.ts
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1630

#1628 add file upload error tests
  functional-test/e2e/urgent-hearing.spec.ts
  functional-test/fixtures/steps/urgent.hearing.ts
  functional-test/pages/action.further.evidence.page.ts
  functional-test/pages/content/action.further.evidence_en.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1628

#1631 feat: add the death to appellant tests
  functional-test/api/client/sscs/appeal.event.ts
  functional-test/common/web.action.ts
  functional-test/e2e/add-note.spec.ts
  functional-test/e2e/appeal-withdrawn.spec.ts
  functional-test/e2e/death-of-an-appellant.spec.ts
  functional-test/e2e/send-to-fta.spec.ts
  functional-test/e2e/urgent-hearing.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/death.of.an.appelant.ts
  functional-test/fixtures/steps/send.to.fta.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/death.of.an.appellant_en.json
  functional-test/pages/death.of.appelant.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1631

#1635 Sscssi 350
  package.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1635

#1629 SSCSSI-347: Add tests for Appeal Dormant event
  functional-test/e2e/appeal-dormant.spec.ts
  functional-test/fixtures/steps/appeal.dormant.ts
  functional-test/lib/steps.factory.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1629

#1632 SSCSSI-183: Create a Bundle Test
  functional-test/e2e/create-a-bundle.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/create.bundle.ts
  functional-test/helpers/stepsHelper.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/create.a.bundle_en.json
  functional-test/pages/create.bundle.ts
  functional-test/pages/tabs/bundles.ts
  package-lock.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1632

#1619 SI-195 link a case event
  functional-test/e2e/link-case.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/link-case.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/link.case_en.json
  functional-test/pages/link.case.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1619
