Repository hmcts/sscs-ccd-definitions, pull requests merged in 2024-03, with the labels that each got.

#1522 SSCS-12361 Prepare for global search / work allocation data migration
  benefit/VERSION.yaml
  benefit/data/ccd-template.xlsx
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/SearchCriteria/SearchCriteria.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1522

#1524 Dwp enhancement merge
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
  benefit/data/sheets/ComplexTypes/ComplexTypes.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
  benefit/data/sheets/SearchResultFields/SearchResultFields.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields.json
  benefit/data/sheets/WorkBasketResultFields/WorkBasketResultFields.json
  e2e-tests/package.json
  e2e-tests/yarn.lock
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1524

#1529 SSCSSI-31: Point sscs-ccd-callback-orchestrator send endpoints to tri…
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1529

#1525 SSCSCI-82: Add joint party contact
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1525

#1541 Update suppressions
  e2e-tests/yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1541

#1545 Added CVE-2024-29041 to suppressions
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1545

#1521 CCD: show list
  benefit/VERSION.yaml
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1521
