Repository hmcts/sscs-ccd-definitions, pull requests merged in 2024-05, with the labels that each got.

#1570 [SSCSSI-238] add associate case tests
  functional-test/common/web.action.ts
  functional-test/e2e/associate-case.spec.ts
  functional-test/fixtures/steps/associate-case.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/associate.case.page.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/associate.case_en.json
  functional-test/pages/tabs/summary.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1570

#1571 SSCSSI-278: Evidence Reminder case tests
  functional-test/e2e/evidence-reminder.spec.ts
  functional-test/fixtures/steps/evidence.reminder.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/common/event.name.event.description.ts
  functional-test/pages/common/homePage.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1571

#1568 Create bundle - fix duplication of page within event
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-WA.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1568

#1573 Work allocation release updates
  benefit/VERSION.yaml
  benefit/data/ccd-template.xlsx
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-WA.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1573

#1565 Add hmrc test user
  Jenkinsfile_CNP
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1565

#1576 Rename CaseEventToFields-testing-noprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-testing-nonprod.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1576

#1577 Work Allocation roll back
  Jenkinsfile_CNP
  benefit/VERSION.yaml
  benefit/data/ccd-template.xlsx
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-WA.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-testing-nonprod.json
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-GS-nonprod.json
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-WA.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-GS.json
  benefit/data/sheets/AuthorisationCaseState/AuthorisationCaseState-WA.json
  benefit/data/sheets/AuthorisationCaseType/AuthorisationCaseType-nonshuttered.json
  benefit/data/sheets/CaseEvent/CaseEvent-WA.json
  benefit/data/sheets/CaseEvent/CaseEvent-testing-nonprod.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-WA.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-dwpUploadResponse.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-testing-nonprod.json
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseField/CaseField-WA.json
  benefit/data/sheets/EventToComplexTypes/EventToComplexTypes-WA.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles-GS.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles-WA-fee-paid.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles-WA.json
  benefit/data/sheets/RoleToAccessProfiles/RoleToAccessProfiles.json
  benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields-WA.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1577

#1578 Fix wa rollback
  Jenkinsfile_CNP
  benefit/VERSION.yaml
  benefit/data/ccd-template.xlsx
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-WA.json
  benefit/data/sheets/CaseField/CaseField-WA.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1578

#1591 SSCS-12483 - Only enable high level data setup on master build
  Jenkinsfile_CNP
  benefit/VERSION.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1591

#1572 Added test for Listing Error event and updating verifyPageContent met…
  functional-test/e2e/listing-error.spec.ts
  functional-test/fixtures/steps/listing.error.ts
  functional-test/lib/steps.factory.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1572

#1589 SSCS-12472 Fix duplicated submit pages in create bundle event
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEventToFields/CaseEventToFields-WA.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1589

#1593 new event for migration
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  benefit/data/sheets/CaseEvent/CaseEvent.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1593

#1594 Case dormant
  .gitignore
  functional-test/api/client/idam/idam.service.ts
  functional-test/api/client/sscs/factory/appeal.type.factory.ts
  functional-test/api/client/sscs/factory/appeal.update.factory.ts
  functional-test/api/data/payload/create-appeal/campip_sya.json
  functional-test/api/data/payload/create-appeal/carersallowance_sandl_sya.json
  functional-test/api/data/payload/create-appeal/child_support_sya.json
  functional-test/api/data/payload/create-appeal/dla_sandl_sya.json
  functional-test/api/data/payload/create-appeal/esa_sya.json
  functional-test/api/data/payload/create-appeal/iidb_sandl_sya.json
  functional-test/api/data/payload/create-appeal/pip_sandl_rep.json
  functional-test/api/data/payload/create-appeal/pip_sandl_rep_ftof.json
  functional-test/api/data/payload/create-appeal/pip_sandl_sya.json
  functional-test/api/data/payload/create-appeal/pip_sya.json
  functional-test/api/data/payload/create-appeal/tax_credit_sya.json
  functional-test/api/data/payload/create-appeal/uc_sandl_video_sya.json
  functional-test/api/data/payload/create-appeal/uc_sya.json
  functional-test/config/config.ts
  functional-test/e2e/case-dormant.spec.ts
  functional-test/fixtures/steps/associate-case.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/evidence.reminder.ts
  functional-test/fixtures/steps/listing.error.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1594

#1598 SSCS-12498 Fix global search
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-GS.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1598
