Repository hmcts/sscs-ccd-definitions, pull requests merged in 2024-08, with the labels that each got.

#1674 Create hearing test code
  functional-test/api/data/payload/create-appeal/pip_sandl_rep.json
  functional-test/api/data/payload/create-appeal/pip_sandl_rep_ftof.json
  functional-test/common/web.action.ts
  functional-test/e2e/hearing-request.spec.ts
  functional-test/e2e/upload-response.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/hearing.ts
  functional-test/fixtures/steps/upload.response.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/hearing.details_en.json
  functional-test/pages/content/upload.response_en.json
  functional-test/pages/listing.requirements.page.ts
  functional-test/pages/tabs/hearings.ts
  functional-test/pages/tabs/listing.requirements.ts
  functional-test/utils/DateUtilsComponent.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1674

#1682 [SSCSSI-295]: add tests for Allocate Case Roles and Create Bundle work allocation task
  Jenkinsfile_CNP
  functional-test/config/config.ts
  functional-test/e2e/create-a-bundle.spec.ts
  functional-test/e2e/prepare.case.for.hearing.spec.ts
  functional-test/e2e/request.info.from.party.spec.ts
  functional-test/e2e/supplementary.response.spec.ts
  functional-test/e2e/upload.document.further.evidence.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/prepare.case.for.hearing.ts
  functional-test/fixtures/steps/upload.response.ts
  functional-test/fixtures/steps/work-allocation/review.incomplete.appeal.task.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/common/loginPage.ts
  functional-test/pages/content/allocate.case.roles.and.create.bundle.task_en.json
  functional-test/pages/content/allocate.role_en.json
  functional-test/pages/content/prepare.case.for.hearing_en.json
  functional-test/pages/prepare.case.for.hearing.page.ts
  functional-test/pages/tabs/roles.and.access.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1682

#1686 [SSCSSI-281]: add Review PHE Request work allocation task tests
  functional-test/e2e/urgent-hearing.spec.ts
  functional-test/e2e/work-allocation/wa.review.phe.request.task.spec.ts
  functional-test/fixtures/steps/review.phe.ts
  functional-test/fixtures/steps/urgent.hearing.ts
  functional-test/pages/content/review.phe.request.task_en.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1686

#1683 Esa tests
  functional-test/e2e/write-and-issue-final-decision.spec.ts
  functional-test/fixtures/steps/write.final.decision.ts
  functional-test/pages/content/write.final.decision_en.json
  functional-test/pages/write.final.decision.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1683

#1536 SSCSCI-792
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1536

#1689 Remove flaky test
  functional-test/e2e/reinstatement.spec.ts
  functional-test/e2e/upload-hearing.spec.ts
  functional-test/e2e/upload-response.spec.ts
  functional-test/e2e/urgent-hearing.spec.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1689

#1688 Enhanced confidentiality tests
  functional-test/e2e/enhanced-confidentiality.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/create.bundle.ts
  functional-test/fixtures/steps/enhanced.confidentiality.ts
  functional-test/fixtures/steps/upload.response.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/action.further.evidence.page.ts
  functional-test/pages/content/action.further.evidence_en.json
  functional-test/pages/content/create.a.bundle_en.json
  functional-test/pages/content/review.confidentiality_en.json
  functional-test/pages/content/upload.response_en.json
  functional-test/pages/review.confidentiality.page.ts
  functional-test/pages/tabs/bundles.ts
  functional-test/pages/tabs/summary.ts
  functional-test/pages/upload.response.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1688

#1692 Introduce new field to determine if warnings needs to be ignored when triggering event from submitted handler
  benefit/VERSION.yaml
  benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
  benefit/data/sheets/CaseField/CaseField.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1692

#1693 Update benefit version
  benefit/VERSION.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1693

#1685 test: add postponement test
  functional-test/common/web.action.ts
  functional-test/e2e/link-case.spec.ts
  functional-test/e2e/postponement.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/link-case.ts
  functional-test/fixtures/steps/postponement.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/add.hearing.page.ts
  functional-test/pages/common/event.name.event.description.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/event.name.event.description_en.json
  functional-test/pages/content/postponement.details_en.json
  functional-test/pages/hearing.booked.page.ts
  functional-test/pages/link.case.page.ts
  functional-test/pages/postponement.page.ts
  functional-test/playwright.config.ts
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1685

#1695 Sscssi 304 referred by admin
  functional-test/e2e/referred-by-admin.spec.ts
  functional-test/fixtures/steps/referred.by.admin.ts
  functional-test/fixtures/steps/send.to.interloc.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/allocate.role_en.json
  functional-test/pages/content/referred.by.admin.task_en.json
  functional-test/pages/content/send.to.interloc_en.json
  functional-test/pages/send.to.interloc.page.ts
  functional-test/pages/tabs/roles.and.access.ts
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1695

#1696 local-dev-setup: port change due to conflict with cftlib docAssembly
  bin/before-data-setup-step.sh
  bin/create-xlsx.sh
  bin/upload-ccd-definition-to-env.sh
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1696

#1699 Local dev setup
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1699

#1698 Sscssi 303 referred by judge
  functional-test/e2e/referred-by-judge.spec.ts
  functional-test/fixtures/steps/referred.by.judge.ts
  functional-test/fixtures/steps/send.case.to.tcw.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/referred.by.judge.task_en.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1698

#1667 SSCSCI-879: Validate DirectionDueDate only when explicitly entered
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
  benefit/data/sheets/CaseEventToFields/CaseEventsToFields-writeAdjournmentNotice.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1667

#1679 Sscssi 297 process audio/video evidence
  Jenkinsfile_CNP
  functional-test/e2e/process-audio-video-evidence.spec.ts
  functional-test/fixtures/steps/process.av.evidence.ts
  functional-test/pages/content/process.audio.video.evidence_en.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1679

#1704 Sscssi 299 abate tcw FTA not Provided Appointee Details
  functional-test/e2e/abate-fta.not.provided.appointee.details.spec.ts
  functional-test/fixtures/steps/fta.not.provided.appointee.details.ts
  functional-test/fixtures/steps/update.not.listable.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/review.fta..not.provided.appointee.details_en.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1704

#1694 SI-300 review fta validity challenge task
  functional-test/e2e/work-allocation/wa.review.fta.validity.challenge.task.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/work-allocation/review.fta.validity.challenge.task.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/review.fta.validity.challenge.task_en.json
  functional-test/pages/review.fta.validity.challenge.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1694

#1697 SI-302 review postponement request task
  functional-test/e2e/work-allocation/wa.review.postponement.request.task.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/work-allocation/review.postponement.request.task.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/postponement.request_en.json
  functional-test/pages/postponement.request.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1697

#1709 SI-307 wa update hearing details
  functional-test/e2e/work-allocation/update.hearing.details.task.spec.ts
  functional-test/fixtures/steps/work-allocation/update.hearing.details.task.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/update.hearing.details.task_en.json
  functional-test/pages/tabs/tasks.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1709

#1711 Hotfix ignore suppressions
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1711

#1717 Sscssi 283 referred by admin judge
  functional-test/e2e/referred-by-admin-judge-task.spec.ts
  functional-test/fixtures/steps/referred.by.admin.judge.task.ts
  functional-test/fixtures/steps/send.to.interloc.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/referred.by.admin.judge.task_en.json
  functional-test/pages/content/send.to.interloc_en.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1717

#1718 Sscssi 275 referred by interloc judge
  functional-test/e2e/referred-to-interloc-judge-task.spec.ts
  functional-test/e2e/referred-to-interloc.spec.ts
  functional-test/fixtures/steps/referred.to.interloc.judge.task.ts
  functional-test/fixtures/steps/send.to.interloc.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/referred.to.interloc.judge.task_en.json
  functional-test/pages/content/send.to.interloc_en.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1718

#1713 SI-284 judge review postponement request task
  functional-test/e2e/work-allocation/wa.judge.review.postponement.request.task.spec.ts
  functional-test/fixtures/steps/work-allocation/judge.review.postponement.request.task.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/judge.review.postponement.request.task_en.json
  functional-test/pages/tabs/tasks.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1713

#1719 SI-288-WA- prepare for hearing judge task
  functional-test/e2e/work-allocation/wa.prepare.for.hearing.task.spec.ts
  functional-test/fixtures/steps/work-allocation/prepare.for.hearing.task.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/allocate.role_en.json
  functional-test/pages/content/prepare.for.hearing.task_en.json
  functional-test/pages/tabs/roles.and.access.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1719

#1720 Sscssi 282 add referred by TCW judge
  functional-test/e2e/referred-by-tcw-judge-task.spec.ts
  functional-test/fixtures/steps/referred.by.tcw.judge.task.ts
  functional-test/fixtures/steps/send.to.judge.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/referred.by.tcw.judge.task_en.json
  functional-test/pages/content/send.to.judge_en.json
  functional-test/pages/send.to.judge.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1720

#1721 Sscssi 276 add abate Judge
  functional-test/e2e/abate-fta.not.provided.appointee,details.judge.task.spec.ts
  functional-test/e2e/abate-fta.not.provided.appointee.details.spec.ts
  functional-test/fixtures/steps/fta.not.provided.appointee.details.judge.task.ts
  functional-test/fixtures/steps/update.not.listable.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/review.fta.not.provided.appointee.details.judge.task_en.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1721

#1723 Sscssi 277 review confidentiality request
  functional-test/e2e/work-allocation/wa.review.confidentiality.request.task.spec.ts
  functional-test/fixtures/steps/work-allocation/review.confidentiality.request.task.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/review.confidentiality.request.task_en.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1723
