Repository hmcts/sscs-ccd-definitions, pull requests merged in 2024-07, with the labels that each got.

#1643 fix failing tests
  functional-test/common/web.action.ts
  functional-test/e2e/urgent-hearing.spec.ts
  functional-test/fixtures/steps/create.bundle.ts
  functional-test/fixtures/steps/link-case.ts
  functional-test/fixtures/steps/upload.response.ts
  functional-test/pages/common/event.name.event.description.ts
  functional-test/pages/link.case.page.ts
  functional-test/pages/upload.response.page.ts
  sonar-project.properties
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1643

#1642 [SSCSSI-266]: Add Review BF date work allocation task tests
  functional-test/e2e/work-allocation/wa.review.bf.date.task.spec.ts
  functional-test/fixtures/steps/appeal.withdrawn.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/mark-case.as.urgent.ts
  functional-test/fixtures/steps/work-allocation/review.bf.date.task.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/allocate.ctsc.role_en.json
  functional-test/pages/content/allocate.role_en.json
  functional-test/pages/content/review.bf.date.task_en.json
  functional-test/pages/link.case.page.ts
  functional-test/pages/tabs/roles.and.access.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1642

#1644 [SSCSSI-263]: add Action Unprocessed correspondence CTSC task work allocation tests
  functional-test/e2e/supplementary.response.spec.ts
  functional-test/e2e/upload.document.further.evidence.spec.ts
  functional-test/e2e/work-allocation/wa.review.admin.action.task.spec.ts
  functional-test/e2e/work-allocation/wa.review.bf.date.task.spec.ts
  functional-test/e2e/work-allocation/wa.review.incomplete.appeal.task.spec.ts
  functional-test/e2e/work-allocation/wa.review.listing.error.task.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/supplementary.response.ts
  functional-test/fixtures/steps/upload.document.further.evidence.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/action.further.evidence.page.ts
  functional-test/pages/content/action.further.evidence_en.json
  functional-test/pages/content/action.unprocessed.correspondence.task_en.json
  functional-test/pages/content/supplementary.response_en.json
  functional-test/pages/content/upload.document.further.evidence_en.json
  functional-test/pages/supplementary.response.page.ts
  functional-test/pages/tabs/tasks.ts
  functional-test/pages/upload.document.further.evidence.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1644

#1647 [SSCSSI-271]: Review bi-lingual document CTSC work allocation task tests
  functional-test/e2e/upload.document.further.evidence.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/cancel.translations.ts
  functional-test/fixtures/steps/create.bundle.ts
  functional-test/fixtures/steps/request.translations.ts
  functional-test/fixtures/steps/update.language.preference.ts
  functional-test/fixtures/steps/upload.document.further.evidence.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/review.bilingual.document.task_en.json
  functional-test/pages/content/update.langauge.preference_en.json
  functional-test/pages/tabs/history.ts
  functional-test/pages/tabs/welsh.ts
  functional-test/pages/update.language.preference.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1647

#1640 SSCSSI 199: Provide Appointee Details tests
  functional-test/e2e/provide-appointee-details.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/create.bundle.ts
  functional-test/fixtures/steps/death.of.an.appelant.ts
  functional-test/fixtures/steps/provide.appointee.details.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/appointee.details_en.json
  functional-test/pages/content/create.a.bundle_en.json
  functional-test/pages/death.of.appelant.ts
  functional-test/pages/provide.appointee.details.page.ts
  functional-test/pages/tabs/appealDetails.ts
  functional-test/playwright.config.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1640

#1648 Sscssi 192 v2
  functional-test/api/client/sscs/factory/appeal.update.factory.ts
  functional-test/api/data/payload/action-further-evidence/action-further-evidence-other.json
  functional-test/api/data/payload/upload-response/upload-response-dwp-022-EC.json
  functional-test/api/data/payload/upload-response/upload-response-hmrc-053-DQ.json
  functional-test/e2e/api-test-client.spec.ts
  functional-test/e2e/issue-directions-notice.spec.ts
  functional-test/e2e/request-time-extension.spec.ts
  functional-test/fixtures/steps/issue.directions.notice.ts
  functional-test/fixtures/steps/reinstatement.ts
  functional-test/fixtures/steps/request.time.extension.ts
  functional-test/fixtures/steps/send.to.fta.ts
  functional-test/fixtures/steps/urgent.hearing.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/common/event.name.event.description.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/action.further.evidence_en.json
  functional-test/pages/content/issue.direction_en.json
  functional-test/pages/content/request.time.extension_en.json
  functional-test/pages/issue.direction.page.ts
  functional-test/pages/tabs/summary.ts
  functional-test/playwright.config.ts
  package-lock.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1648

#1649 upload phe tests
  functional-test/e2e/upload-response.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/death.of.an.appelant.ts
  functional-test/fixtures/steps/review.phe.ts
  functional-test/fixtures/steps/upload.response.ts
  functional-test/helpers/stepsHelper.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/common/check.your.answers.page.ts
  functional-test/pages/content/create.a.bundle_en.json
  functional-test/pages/content/review.phe_en.json
  functional-test/pages/review.phe.page.ts
  functional-test/pages/tabs/bundles.ts
  functional-test/pages/tabs/history.ts
  functional-test/pages/tabs/summary.ts
  functional-test/pages/upload.response.page.ts
  functional-test/playwright.config.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1649

#1650 SI-212 Update subscription test
  functional-test/e2e/update-subscription.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/update.subscription.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/update.subscription.data_en.json
  functional-test/pages/tabs/subscriptions.ts
  functional-test/pages/update.subscription.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1650

#1651 UCB tests
  functional-test/e2e/upload-response.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/update.ucb.ts
  functional-test/fixtures/steps/upload.response.ts
  functional-test/helpers/stepsHelper.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/common/check.your.answers.page.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/update.ucb_en.json
  functional-test/pages/tabs/listing.requirements.ts
  functional-test/pages/update.ucb.page.ts
  functional-test/pages/upload.response.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1651

#1652 [SSCSSI-279]: add Review Reinstatement Request - Judge work allocation task tests
  Jenkinsfile_CNP
  functional-test/config/config.ts
  functional-test/e2e/reinstatement.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/reinstatement.ts
  functional-test/fixtures/steps/send.to.admin.ts
  functional-test/fixtures/steps/urgent.hearing.ts
  functional-test/pages/action.further.evidence.page.ts
  functional-test/pages/amend.interloc.review.state.page.ts
  functional-test/pages/common/event.name.event.description.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/amend.interloc.review.state_en.json
  functional-test/pages/content/assign.task_en.json
  functional-test/pages/content/review.reinstatement.request.task_en.json
  functional-test/pages/content/tasks_en.json
  functional-test/pages/tabs/appealDetails.ts
  functional-test/pages/tabs/tasks.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1652

#1657 SI-208-210 update other party data scenarios
  functional-test/e2e/update-other-party-data.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/update.other.party.data.ts
  functional-test/fixtures/steps/update.subscription.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/update.other.party.data_en.json
  functional-test/pages/tabs/other.party.details.ts
  functional-test/pages/update.other.party.data.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1657

#1659 Fix failing WA tests
  functional-test/e2e/supplementary.response.spec.ts
  functional-test/e2e/upload.document.further.evidence.spec.ts
  functional-test/fixtures/steps/supplementary.response.ts
  functional-test/fixtures/steps/upload.document.further.evidence.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1659

#1601 SSCSCI-860: Update related cases tab show condition
  benefit/VERSION.yaml
  benefit/data/sheets/CaseEvent/CaseEvent.json
  benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1601

#1655 Sscssi 270 add review information requested
  functional-test/e2e/request.info.from.party.spec.ts
  functional-test/fixtures/steps/request.info.from.party.ts
  functional-test/pages/content/review.information.requested.task_en.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1655

#1660 [SSCSSI-280]: Add Review Urgent Hearing Request - Judge work allocation task tests
  functional-test/e2e/urgent-hearing.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/reinstatement.ts
  functional-test/fixtures/steps/urgent.hearing.ts
  functional-test/pages/content/allocate.role_en.json
  functional-test/pages/content/review.urgent.hearing.request.task_en.json
  functional-test/pages/content/send.case.to.tcw_en.json
  functional-test/pages/send.case.to.tcw.page.ts
  functional-test/pages/tabs/roles.and.access.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1660

#1661 Process evidence tests
  functional-test/api/client/sscs/factory/appeal.update.factory.ts
  functional-test/api/data/payload/upload-response/upload-response-dwp-av-002-PIP.json
  functional-test/e2e/process-audio-video-evidence.spec.ts
  functional-test/e2e/reinstatement.spec.ts
  functional-test/e2e/upload.document.further.evidence.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/process.av.evidence.ts
  functional-test/fixtures/steps/upload.document.further.evidence.ts
  functional-test/fixtures/steps/upload.response.ts
  functional-test/helpers/stepsHelper.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/common/check.your.answers.page.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/audio.video.evidence_en.json
  functional-test/pages/content/upload.document.further.evidence_en.json
  functional-test/pages/content/upload.response_en.json
  functional-test/pages/issue.direction.page.ts
  functional-test/pages/process.av.page.ts
  functional-test/pages/tabs/audioVideoEvidence.ts
  functional-test/pages/tabs/roles.and.access.ts
  functional-test/pages/upload.response.page.ts
  functional-test/playwright.config.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1661

#1658 Sscssi 187
  functional-test/api/client/sscs/factory/appeal.update.factory.ts
  functional-test/api/data/payload/create-appeal/pip_incomplete_appeal.json
  functional-test/api/data/payload/upload-response/upload-response-dwp-022-CC.json
  functional-test/e2e/api-test-client.spec.ts
  functional-test/e2e/issue-directions-notice.spec.ts
  functional-test/e2e/write-and-issue-final-decision.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/issue.directions.notice.ts
  functional-test/fixtures/steps/write.final.decision.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/send.to.interloc_en.json
  functional-test/pages/content/write.final.decision_en.json
  functional-test/pages/send.to.interloc.prevalid.page.ts
  functional-test/pages/write.final.decision.page.ts
  functional-test/utils/DateUtilsComponent.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1658

#1662 SSCSSI-207 update not listable
  functional-test/e2e/update-not-listable.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/update.not.listable.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/update.not.listable_en.json
  functional-test/pages/not.listable.page.ts
  functional-test/pages/update.not.listable.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1662

#1665 SSCSSI-203 search filter scenario
  functional-test/e2e/search-filter.spec.ts
  functional-test/e2e/update-not-listable.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/search.filter.ts
  functional-test/fixtures/steps/update.not.listable.ts
  functional-test/fixtures/steps/update.subscription.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/common/homePage.ts
  functional-test/pages/content/search.filter_en.json
  functional-test/pages/not.listable.page.ts
  functional-test/pages/search.filter.page.ts
  functional-test/pages/update.not.listable.page.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1665

#1668 Sscssi 301 review time extenstion request
  Jenkinsfile_CNP
  functional-test/config/config.ts
  functional-test/e2e/request-time-extension.spec.ts
  functional-test/fixtures/steps/request.time.extension.ts
  functional-test/pages/content/issue.direction_en.json
  functional-test/pages/content/review.fta.time.extension.request.task_en.json
  functional-test/pages/tabs/tasks.ts
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1668

#1670 SI-202 reissue further evidence
  functional-test/e2e/reissue-further-evidence.spec.ts
  functional-test/fixtures/steps/base.ts
  functional-test/fixtures/steps/reissue.further.evidence.ts
  functional-test/lib/steps.factory.ts
  functional-test/pages/content/reissue.further.evidence_en.json
  functional-test/pages/reissue.further.evidence.page.ts
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-definitions-pr-1670
